name: womentechies_20_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  page_transition:
  font_awesome_flutter:
  snaplist:
  http:
  shared_preferences:
  qr_flutter:
  flutter_webview_plugin:
  url_launcher:
  fluttertoast:
  flip_card:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - dsc-logo.png
    - logo-orange.png
    - speaker1.jpeg
    - speaker2.jfif
    - women.png
    - assets/sponsors/balsamiq.png
    - assets/sponsors/bugsee.png
    - assets/sponsors/cloudsploit.png
    - assets/sponsors/cmr.png
    - assets/sponsors/goel.png
    - assets/sponsors/jetbrains.png
    - assets/sponsors/nkcc.png
    - assets/sponsors/sketch.png
    - assets/core/ABDEALI.webp
    - assets/core/AdityaMadan.webp
    - assets/core/AkshatGupta.webp
    - assets/core/AmoghLele.webp
    - assets/core/AnanyaG.webp
    - assets/core/angadsharma.webp
    - assets/core/AnshulBamb.webp
    - assets/core/ArjunBhanot.webp
    - assets/core/ArushiJain.webp
    - assets/core/AshutoshKaushik.webp
    - assets/core/AviralChauhan.webp
    - assets/core/ChanakyaKapoor.webp
    - assets/core/ChiyaBorkar.webp
    - assets/core/DeepakMalpani.webp
    - assets/core/DeepakNahar.webp
    - assets/core/EkaanshArora.webp
    - assets/core/FenilJain.webp
    - assets/core/GovindKrishnan.webp
    - assets/core/GurnehmatDhindsa.webp
    - assets/core/HardikKataria.webp
    - assets/core/IshiYadav.webp
    - assets/core/JanviPrasad.webp
    - assets/core/kritikasharma.webp
    - assets/core/Kush.webp
    - assets/core/ManoramaM.webp
    - assets/core/MayankKumar.webp
    - assets/core/MdHishaamAkhtar.webp
    - assets/core/meherdeepthakur.webp
    - assets/core/MuskanRastogi.webp
    - assets/core/NeilKavalakkat.webp
    - assets/core/NirmitJatana.webp
    - assets/core/PragatiBhattad.webp
    - assets/core/prakharsoni.webp
    - assets/core/PranavRaaghav.webp
    - assets/core/PrateekMewara.webp
    - assets/core/PurushottamSharma.webp
    - assets/core/RamanStudios.webp
    - assets/core/RiddhiGupta.webp
    - assets/core/RithikJain.webp
    - assets/core/RohitMenon.webp
    - assets/core/RuchicaSinha.webp
    - assets/core/SaiSandeepRayanuthala.webp
    - assets/core/SaloniParekh.webp
    - assets/core/SatkritiSingh.webp
    - assets/core/ShantanuVerma.webp
    - assets/core/ShivanshTiwari.webp
    - assets/core/SiddharthaVerma.webp
    - assets/core/SrinjaySaha.webp
    - assets/core/SwayamS.Sharma.webp
    - assets/core/TanmaySrivastava.webp
    - assets/core/ThanmayV.webp
    - assets/core/UbaidUsmani.webp
    - assets/core/VishaalSelvaraj.webp
    - assets/core/Yuvraj.webp
    - assets/core/Sanchi.webp
    - assets/core/magicalduck.webp
    - assets/core/nikal.webp
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
